version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taller_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: db_taller
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - taller-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: taller_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - taller-network
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      args:
        APP_NAME: api-gateway
    container_name: taller_api_gateway
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=super_secret_jwt_key
    depends_on:
      - workshop-service
      - inventory-service
    networks:
      - taller-network

  workshop-service:
    build:
      context: .
      args:
        APP_NAME: workshop-service
    container_name: taller_workshop_service
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://root:rootpassword@postgres:5432/db_taller?schema=public
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JWT_SECRET=super_secret_jwt_key
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - taller-network

  inventory-service:
    build:
      context: .
      args:
        APP_NAME: inventory-service
    container_name: taller_inventory_service
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://root:rootpassword@postgres:5432/db_inventory?schema=public
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - taller-network

  notifications-service:
    build:
      context: .
      args:
        APP_NAME: notifications-service
    container_name: taller_notifications_service
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - taller-network

volumes:
  pgdata:

networks:
  taller-network:
    driver: bridge
